# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rq4NK2epA-5npA2S-_z2Z4PMcB60VPUQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Online Sales Data.csv")
df

df.shape

df.info()

df.isnull().sum()

df.describe(include='all')

# Check for mismatched revenue
df['Check_Revenue'] = df['Units Sold'] * df['Unit Price']

df



